meta_product_name: "AQUATURA"
meta_title: "AQUATURA - take care of your plants"
meta_description: "This app will help you to take care of your plants and improve their lifetime"
meta_image: "https://res.cloudinary.com/dwhcqxkxh/image/upload/v1630570959/aquatura-image_whders.jpg" # should exist in `app/assets/images/`
twitter_account: "@thaisderodez"   # required for Twitter Cards
